# -*- coding: utf-8 -*-
"""duzypdf

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YjkOQzUt6DTAyD4hKOg8alHH281aCf3M
"""

#!pip install PyPDF2 
from PyPDF2 import PdfWriter, PdfReader
import os, math
def split_pdf(plik, pliki,strony):
  reader = PdfReader(plik)
  writer = PdfWriter()
  p=0
  for page in reader.pages:
    p+=1
  ile=math.ceil(p/strony)
  for i in range(ile):
    reader = PdfReader(plik)
    writer = PdfWriter()
    for j in range(10):
      try:
        writer.add_page(reader.pages[i*strony+j])
      except:
        pass
    with open(pliki+f"strony{i*strony+1}-{i*strony+strony}"+".pdf", "wb") as fp:
      writer.write(fp)

def duzypdf():
  ''''''
  for plik in "\content\":
    if plik != "/content/AM2_MAT1697_prezentacja_1.pdf":
      reader = PdfReader(plik)
      writer = PdfWriter()
      for j in range(reader.pages):
        writer.add_page(reader.pages[j])
      with open(duzy+".pdf", "wb") as fp:
        writer.write(fp)
plik=r"/content/AM2_MAT1697_prezentacja_1.pdf"
pliki=r"/content/male-pliki_"
duzy=r"/content/duzy"
#split_pdf(plik, pliki,15)
duzypdf()