# -*- coding: utf-8 -*-
"""l3_z4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYauK8A1AMPk2vNiU3OxMdUhQna94oZm
"""

# wygeneruje i odczyta kody QR (wskazówka: qrcode i OpenCV
#!pip install qrcode
import qrcode
def generowanie(a):
  img = qrcode.make(a)
  img.save("kod_qr")

generowanie(r"https://www.youtube.com/watch?v=dQw4w9WgXcQ")
'''from pyzbar.pyzbar import decode
from PIL import Image
decocdeQR = decode(Image.open('instagram.png'))
print(decocdeQR[0].data.decode('ascii'))'''

"""https://www.makeuseof.com/how-to-create-and-decode-a-qr-code-using-python/
https://note.nkmk.me/en/python-opencv-qrcode/
https://pypi.org/project/qrcode/

"""

!pip install cv2
import cv2
def dekodowanie(a):
  image = cv2.imread(a)
  detector = cv2.QRCodeDetector()
  data, vertices_array, binary_qrcode = detector.detectAndDecode(image)
  if vertices_array is not None:
    print(data)
  else:
    print("There was some error")
'''
std::string cv::QRCodeDetector::detectAndDecode	(	InputArray 	img,
OutputArray 	points = noArray(),
OutputArray 	straight_qrcode = noArray() 
)	
'''
dekodowanie("/content/some_file (1).png")