# -*- coding: utf-8 -*-
"""lepsza_kopia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YP0a6wxVx4hOxltnxAlqV9OwaeUZTk5C
"""

import os
import shutil
from time import time 
from datetime import date
 
def lepsza_kopia(sciezka, rozszerzenie,):

	'''#Całkowicie zbędne, ale wypisze nam jakie pliki były modyfikowane :).
	for file in os.listdir(a):
		if file.endswith(b):
			print(os.path.join(a, file))
 '''
 
	#tm() to czas teraźniejszy w sekundach, odejmujemy trzy dni w sekundach (60 sek w minucie, 60 min w godzinie, 24 godziny w dniu, razy 3 dni)
	do_backup=time()-(60*60*24*3)
	#Tu jest data ładnie pokazana w formie rok, mc, dzień
	data = date.today()
 
	#Katalog backup i ścieżka docelowa, zaczynająca się w miejscu odpalenia programu.
	kopia="Backup\copy-"+str(data)
	os.makedirs(kopia, exist_ok=True)
 
	#Lista plików znalezionych w ścieżce 'a'
	src_files = os.listdir(a)
	#Przelatujemy po elementach listy utworzonej wyżej sprawdzając każdy plik.
	for file_name in src_files:
		#Łączymy ścieżkę w jedną nazwę
		full_file_name = os.path.join(a, file_name)
		#Odczytujemy w sekundach kiedy dany plik został zmodyfikowany
		file_date=os.stat(full_file_name).st_mtime
		#Jeśli teraz minus 3 dni w sekundach jest mniejsze od daty pliku to...
		if do_backup<file_date:
			#I jeśli plik kończy się na wskazane rozszerzenie.
			if full_file_name.endswith(b):
				#To wykona jego kopię w folderze wyjściowym - backup'owym
				shutil.copy(full_file_name, kopia)