# -*- coding: utf-8 -*-
"""l2.z3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_tz5uKjp-vE-GA1sMPCQ7yt4r43BwJUI
"""

#tworzy kopie bezpieczeństwa, zapisując wybrane katalogi do archiwów zip. Nazwy tych archiwów powinny zawierać aktualną datę jako
#przedrostek. (Wskazówka: moduł zipfile).

import os
from zipfile import ZipFile

# Create a ZipFile Object
with ZipFile('E:/Zipped file.zip', 'w') as zip_object:
   # Adding files that need to be zipped
   zip_object.write('E:/Folder to be zipped/Greetings.txt')
   zip_object.write('E:/Folder to be zipped/Introduction.txt')

# Check to see if the zip file is created
if os.path.exists('E:/Zipped file.zip'):
   print("ZIP file created")
else:
   print("ZIP file not created")

import os
from zipfile import ZipFile

# Create object of ZipFile
with ZipFile('E:/Zipped file.zip', 'w') as zip_object:
   # Traverse all files in directory
   for folder_name, sub_folders, file_names in os.walk('E:/Folder to be zipped'):
      for filename in file_names:
         # Create filepath of files in directory
         file_path = os.path.join(folder_name, filename)
         # Add files to zip file
         zip_object.write(file_path, os.path.basename(file_path))

if os.path.exists('E:/Zipped file.zip'):
   print("ZIP file created")
else:
   print("ZIP file not created")

"""https://www.tutorialspoint.com/How-to-create-a-zip-file-using-Python#
https://pl.python.org/forum/index.php?action=printpage;topic=1862.0
https://pl.python.org/forum/index.php?topic=1559.0;wap2
https://doraprojects.net/questions/123198/how-do-i-copy-a-file-in-python

"""

import os
from zipfile import ZipFile

def zip_csv(directory_name, zip_file_name, filter):
   # Create object of ZipFile
   with ZipFile(zip_file_name, 'w') as zip_object:
   # Traverse all files in directory
   for folder_name, sub_folders, file_names in os.walk(directory_name):
      for filename in file_names:
      # Filter for csv files
      if filter(filename):
         # Create filepath of files in directory
         file_path = os.path.join(folder_name, filename)
         # Add files to zip file
         zip_object.write(file_path, os.path.basename(file_path))

if __name__ == '__main__':
   zip_csv('E:/Folder to be zipped', 'E:/Zipped file.zip', lambda name: 'csv' in name)
if os.path.exists('E:/Zipped file.zip'):
   print("ZIP file created with only CSV files")
else:
   print("ZIP file not created")

from zipfile import ZipFile
import shutil, os

def kopia(sciezka, sciezka_kopii):
  if type(sciezka) == list:
    for i in sciezka:
      if os.path.isfile(i):
        shutil.copyfile(i, sciezka_kopii)
      if os.path.isdir(i):
        shutil.copytree(i, sciezka_kopii)
  else:
    if sciezka.isfile():
        shutil.copyfile(sciezka, sciezka_kopii)
    if sciezka.isdir():
        shutil.copytree(sciezka, sciezka_kopii)
  with ZipFile(sciezka_kopii, 'w') as zip_object:
    for katalog, podkatalogi, pliki in os.walk(sciezka_kopii):
      for plik in pliki:
         sciezka_pliku = os.path.join(katalog, plik)
         zip_object.write(file_path, os.path.basename(sciezka_pliku))

lista=['/content/1679605707220.jpg','/content/1679605822857.jpg','/content/1679605846690.jpg']
kopia(lista, '/content')